"""Add recipe_associations table

Revision ID: df0f86025c2f
Revises: b1020f328e98
Create Date: 2024-12-29 03:29:41.833346

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "df0f86025c2f"
down_revision: str | None = "b1020f328e98"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "recipe_associations",
        sa.Column("id", mealie.db.migration_types.GUID(), primary_key=True, nullable=False),
        sa.Column("recipe_id", mealie.db.migration_types.GUID(), sa.ForeignKey("recipes.id"), nullable=False),
        sa.Column(
            "associated_recipe_id", mealie.db.migration_types.GUID(), sa.ForeignKey("recipes.id"), nullable=False
        ),
        sa.Column("quantity", sa.Float(), nullable=False, default=1.0),
        sa.UniqueConstraint("recipe_id", "associated_recipe_id", name="uq_recipe_associated_recipe"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipe_associations")
    # ### end Alembic commands ###
