"""'Add sections for ingredients'

Revision ID: 0824283b9579
Revises: 1d9a002d7234
Create Date: 2025-11-05 15:14:03.300516

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "1ee9f4c2be01"
down_revision: str | None = "1d9a002d7234"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipe_ingredient_section",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("recipe_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recipe_ingredient_section", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recipe_ingredient_section_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_recipe_ingredient_section_position"), ["position"], unique=False)
        batch_op.create_index(batch_op.f("ix_recipe_ingredient_section_recipe_id"), ["recipe_id"], unique=False)

    with op.batch_alter_table("recipes_ingredients", schema=None) as batch_op:
        batch_op.add_column(sa.Column("section_id", mealie.db.migration_types.GUID(), nullable=True))
        batch_op.create_index(batch_op.f("ix_recipes_ingredients_section_id"), ["section_id"], unique=False)
        batch_op.create_foreign_key("fk_ingredient_section", "recipe_ingredient_section", ["section_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipes_ingredients", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_recipes_ingredients_section_id"))
        batch_op.drop_column("section_id")

    with op.batch_alter_table("recipe_ingredient_section", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipe_ingredient_section_recipe_id"))
        batch_op.drop_index(batch_op.f("ix_recipe_ingredient_section_position"))
        batch_op.drop_index(batch_op.f("ix_recipe_ingredient_section_created_at"))

    op.drop_table("recipe_ingredient_section")
    # ### end Alembic commands ###
